### ISSUE TITLE
Using deprecated MMD4. Can we update to MMD5?

### ISSUE THREAD

**Issue by jesperronn** [tillsc/multi_markdown#7]
This is the message from the linked MMD4 repository:

> This project is now deprecated. Please use MultiMarkdown-5 instead! 

I briefly read through https://github.com/fletcher/MultiMarkdown-5/releases and could not immediately spot breaking issues.

Have anybody made an attempt to upgrade?
What are the plans for maintaining this project?

**Comment by tillsc** [comment]
I'm working on supporting MMD6. Since @fletcher changed the whole build it isn't as easy as I had hoped. 

WIP: https://github.com/tillsc/multi_markdown/tree/v-6 (doesn't work jet with linker problems)

**Comment by jesperronn** [comment]
Thanks for the update 👍

**Comment by tillsc** [comment]
See #8
